# Numpy

In [1]:
# Import the numpy package as np, so that you can refer to numpy with np.
import numpy as np

In [2]:
np_arr=np.array([1,2,3,4,5,6])

np_arr[0]

1

In [3]:
list1=[1,2,3,4,5,6,7]
np_arr1=np.array(list1)
np_arr1

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
tup=(1,2,3,4)
np_arr2=np.array(tup)
np_arr2

array([1, 2, 3, 4])

In [5]:
set1={1,2,3,4}
np_arr3=np.array(set1)
np_arr3
#it give error np_arr3[0]

array({1, 2, 3, 4}, dtype=object)

In [6]:
print(type(np_arr),type(np_arr1),type(np_arr2),type(np_arr3))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


### Comparison of List & Numpy

In [9]:
arr=np.array([1,2,3])
arr1=np.array([2,3,4])
print(arr+arr1)

[3 5 7]


In [10]:
print(arr1*2)

[4 6 8]


In [11]:
arr3=np.array(arr1)
arr3

array([2, 3, 4])

### Datatypes in Numpy

In [7]:
arr = np.array(['apple','banana','orange'])
print(arr,arr.dtype)

['apple' 'banana' 'orange'] <U6


In [18]:
arr=np.array([1,'j'])
print(arr,arr.dtype)

['1' 'j'] <U11


In [8]:
arr=np.array([(1,),(2,)])
print(arr,arr.dtype)

[[1]
 [2]] int32


In [9]:
dt = np.dtype([('age',np.int8)])
dt

dtype([('age', 'i1')])

In [10]:
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a)

[(10,) (20,) (30,)]


In [11]:
dt = np.dtype([('name','S10'),('age',np.int8)])
dt

dtype([('name', 'S10'), ('age', 'i1')])

In [15]:
b = np.array([('abc',1),('xyz',2)], dtype=dt)
print(b)

[(b'abc', 1) (b'xyz', 2)]


### 2D Numpy Arrays

We'll cover a few categories of basic array manipulation :
* Attributes of Array
* Indexing of Arrays
* Slicing of Arrays
* Reshaping of Arrays
* Joining and spliting

#### Attributes of Array

In [12]:
#this array attribute return the number of dimension
arr=np.arange(12)
arr.ndim

1

In [13]:
#this array attribute return the shape
print(arr.shape)
arr=np.array([[2,3,4],[4,5,6]])
arr.shape

(12,)


(2, 3)

In [14]:
#this return the size
arr.size

6

In [15]:
#this return the memory allocation
arr.itemsize

4

In [16]:
#this return the total memory allocation
arr.nbytes

24

In [17]:
#it return the data type 
arr.dtype

dtype('int32')

#### Array Indexing

In [19]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
print(arr1[0])
print(arr2[0])
print(arr2[0,0])
print(arr2[0][0])

1
[1 2 3]
1
1


In [22]:
#-1 also indicate the last value of numpy array
print(arr[-1])
print(arr2[-1][0])

[4 5 6]
7


In [28]:
arr3=np.random.randint(10,size=(3,4,5))
arr3

array([[[3, 1, 0, 2, 8],
        [7, 0, 4, 7, 2],
        [2, 8, 0, 7, 9],
        [8, 4, 5, 9, 1]],

       [[6, 6, 9, 9, 6],
        [3, 5, 3, 8, 6],
        [3, 8, 4, 1, 4],
        [3, 4, 8, 9, 8]],

       [[1, 1, 0, 0, 9],
        [8, 1, 4, 4, 9],
        [2, 7, 4, 9, 3],
        [9, 2, 9, 9, 0]]])

In [29]:
arr3[0,-1,3]

9

**Slicing**

In [24]:
print(arr1[0:3])
print(arr1[-1::2])
print(arr1[::-2])
print(arr1[::2])
print(arr1[-1:0:1])
print(arr1[-1:0:-1])
print(arr1[-2:0:-2])

[1 2 3]
[6]
[6 4 2]
[1 3 5]
[]
[6 5 4 3 2]
[5 3]


In [25]:
print(arr2)
print(arr2[0:1,-1:0:-2])
print(arr2[0:1,-1:0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3]]
[]


In [41]:
print(arr3[::,0:3,::-2])

[[[8 0 3]
  [2 4 7]
  [9 0 2]]

 [[6 9 6]
  [6 3 3]
  [4 4 3]]

 [[9 0 1]
  [9 4 8]
  [3 4 2]]]


**RESHAPE**

In [26]:
arr1=np.array([1,2,3,4,5,6,7,8])
arr2=np.array([[[1,2,3,4],[5,6,7,8]],[[9,2,4,4],[10,16,75,8]]])

In [27]:
x=arr1.reshape(4,2)
# resize() consider that
x

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**Concatentation and Spliting**

In [53]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [55]:
print(np.concatenate([x,y]))

[1 2 3 4 5 6]


In [56]:
print(np.vstack([x,y]))

[[1 2 3]
 [4 5 6]]


In [57]:
z=np.vstack([x,y])
h=np.array([[99],[99]])
print(np.hstack([h,z]))

[[99  1  2  3]
 [99  4  5  6]]


In [78]:
#Spliting
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr2=np.array([1,5,2,0,0,5,3,4])

In [60]:
x1,x2,x3=np.split(arr1,3)
print(x1,x2,x3)

[1 2 3] [4 5 6] [7 8 9]


In [79]:
x1,x2,x3,x4=np.split(arr2,[4])
print(x1,x2,x3)
#dsplit,vsplit

ValueError: not enough values to unpack (expected 4, got 2)

## Array Creating

the below methods return an array as a result

In [4]:
#Zeros()
print(np.zeros(10,dtype=int))
print(np.zeros((3,5),dtype=int))

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [5]:
#ones()
print(np.ones((3,2,2),dtype=float))

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [6]:
np.full(4,5)

array([5, 5, 5, 5])

In [7]:
print(np.arange(0,20,3))

[ 0  3  6  9 12 15 18]


In [8]:
print(np.linspace(0,5,10))
#create an array of ten vlues evenly spaced between 0 and 5

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


**random()**

In [1]:
np.random.random((3,3))

NameError: name 'np' is not defined

In [21]:
np.random.normal(0,2,(3,3)) #mean 0 stanard deviation 2

array([[ 1.26392918, -5.06575007,  1.47273566],
       [-0.77563097,  0.52790744,  0.51695845],
       [-1.86431476, -3.38151247,  1.22483601]])

In [11]:
np.random.randint(0,10,(3,3))

array([[1, 4, 6],
       [9, 4, 0],
       [6, 9, 6]])

In [18]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
np.empty(3)

array([1.35021145e-311, 0.00000000e+000, 1.15313172e+214])